module: MyKit
author: Hai Nguyen
author_url: http://aquarchitect.github.io
github_url: https://github.com/aquarchitect/MyKit.git
copyright: '© 2016 [Hai Nguyen](http://aquarchitect.github.io)'

clean: true
exclude:
  - "Sources/iOS/Extensions/Draw+.swift"

readme: Resources/Introduction.md

skip_undocumented: true
hide_documentation_coverage: false

xcodebuild_arguments: [-scheme, MyKit-iOS, -toolchain, com.apple.dt.toolchain.XcodeDefault]

custom_categories:
  - name: Utilities
    children:
    - Arbitrary
    - Curry
    - Promise
    - Result
    - Schedule
    - Change
    - Matrix
    - Box
    - Then
  - name: Native Extension
    children:
    # - String
    - Collection
