language: objective-c
osx_image: xcode8
sudo: required

notifications:
  email: false
  slack: true

branches:
  except:
  - gh-pages

env:
  global:
    - MESSAGE=$(git log --oneline -1)
    - JOB=$(echo $MESSAGE | awk -F '[][]' '{print $2}')

before_install:
  - brew update

install:
  - gem install fastlane
  - if [[ "$JOB" == "doc" || "$JOB" == "release" ]]; then
        brew unlink node && brew install npm;
        npm install -g html-minifier clean-css;
        gem install jazzy;
    fi

before_script:
  - git config --global user.name "Hai Nguyen"
  - git config --global user.email "aquarchitecture@gmail.com"
  - fastlane run carthage command:update

script:
  - if [ "$TRAVIS_TAG" == "" ]; then fastlane test; fi

after_success:
  - if [[ "$TRAVIS_TAG" == "" ]]; then
        if [[ "$JOB" == "tag" || "$JOB" == "release" ]]; then fastlane tag; fi;
        if [[ "$JOB" == "doc" || "$JOB" == "release" ]]; then fastlane doc; fi;
    fi

deploy:
  provider: releases
  api_key:
    secure: sSWWXodyA0HQXkJE99L7GObRtwadZ0eNIozJ2Pej1mm43OuRQtb40ZMMffcHPp14+o+cIATwXfGQr8tMBrf8R6SM1OX7SY6cm6mFFHgsI24bYKt0f+mpirhdMA01neeEr062Qrh6raEZFYBGXRRb1ZrRKJ2uCORlgPZV1Fcn9JIziajS4hzFhZ1mDK8qur+wiCAG5LWG1k1ktkD3OK7Ws87IiZgt69DavodZrHfHc6fw6gQo4ugO5yIVW7Zt1wd1p0Q/i1EaemGUD+wSYlMDS7V7yNjjUj0tzWBH/ow2ae5WB+g/LzJa/B6CVbEdnd1FrMzgnOSXpTlyekv05iyh9CF919/i/m6Q/x23Zhq688PVyjqg3P6fuU4yZZ5evTtt2djLbYYait3VI4+QWZ1SzvCspX5k2U+KTB/4SnYvVKDqgF/vrh7WZz5dSAJg+dKFs63eZXd+5mQuaQvBYpIeuw2KDC0d80pjXp0aBxWoruuiMN9OuOd9iOezmSXDjv29YzkpLLhYFmxJxLXHp3L1KC020dDoUoAOGDoT8d711j80UDapVvAR7d2rwjP84qJQMdlBjaMpWoThvtRz/jjQHITEP3v82BHH2+ZMm38SM3VBitCmxu+mv9iMPmlw+8Z8T8JfegcGb9+M3nMnNfS4w6rsFiUy3S1j2TCzsZIyuA4=
  skip_cleanup: true
  on:
    tags: true
    repo: aquarchitect/MyKit
    condition: $SCHEME = iOS && $JOB = release
