language: objective-c
osx_image: xcode7.2

notifications:
  email: false

env:
  global:
    - FRAMEWORK="MyKit"
    - OSX_SDK=macosx10.11
    - IOS_SDK=iphonesimulator9.2
  matrix:
    - SCHEME="OSX"  SDK=$OSX_SDK  ACTION="build"
    - SCHEME="iOS"  SDK=$IOS_SDK  ACTION="build"

script:
  - xcodebuild -version
  - xcodebuild -showsdks
  - xcodebuild
    -project "$FRAMEWORK.xcodeproj"
    -scheme "$FRAMEWORK-$SCHEME"
    -sdk "$SDK"
    -configuration Debug
    CODE_SIGN_IDENTITY=""
    CODE_SIGNING_REQUIRED=NO
    ONLY_ACTIVE_ARCH=NO
    GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES
    GCC_GENERATE_TEST_COVERAGE_FILES=YES
    "$ACTION"

after_success:
  - bash <(curl -s https://codecov.io/bash)
