language: objective-c
osx_image: xcode7.2

notifications:
  email: false

branches:
  only:
    - master

env:
  global:
    - FRAMEWORK="MyKit"
    - OSX_SDK=macosx10.11
    - IOS_SDK=iphonesimulator9.2
  matrix:
    - DESTINATION="arch=x86_64"             SCHEME="OSX"    SDK=$OSX_SDK    ACTION="test"
    - DESTINATION="OS=9.0,name=iPhone 5S"   SCHEME="iOS"    SDK=$IOS_SDK    ACTION="test"

script:
  - xcodebuild
    -verbose
    -project "$FRAMEWORK.xcodeproj"
    -scheme "$FRAMEWORK-$SCHEME"
    -sdk "$SDK"
    -destination "$DESTINATION"
    -configuration Debug
    CODE_SIGN_IDENTITY=""
    CODE_SIGNING_REQUIRED=NO
    ONLY_ACTIVE_ARCH=NO
    GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES
    GCC_GENERATE_TEST_COVERAGE_FILES=YES
    "$ACTION"

after_success:
  - bash <(curl -s https://codecov.io/bash)
