language: objective-c
osx_image: xcode7.3
sudo: required

notifications:
  email: false

branches:
  only:
    - master

before_install:
  - brew update
  - make fetch

install:
  - git submodule init
  - git submodule update
  - gem install jazzy
  - gem install xcpretty

env:
  global:
    - FRAMEWORK="MyKit"
    - OSX_SDK=macosx10.11
    - IOS_SDK=iphonesimulator9.3
  matrix:
    - DESTINATION="arch=x86_64"             SCHEME="OSX"    SDK=$OSX_SDK
    - DESTINATION="OS=9.0,name=iPhone 5S"   SCHEME="iOS"    SDK=$IOS_SDK

script:
  - make test

after_success:
  - if [[ "$SCHEME" == "iOS" ]]; then make docs; fi
  - make icons