language: objective-c
osx_image: xcode7.2
xcode_scheme:
	- MyKitiOS
	- MyKitOSX
xcode_sdk:
	- iphonesimulator9.2
	- macosx10.11
notifications:
	email: false
branches:
	only:
		- master

# script:
# - xcodebuild -project MyKit.xcodeproj -target MyKitiOS -sdk iphonesimulator9.2
# - xcodebuild -project MyKit.xcodeproj -target MyKitOSX -sdk macosx10.11