fastlane_version "1.104.0"

before_all do
  ENV["SLACK_URL"] = "https://hooks.slack.com/services/#{ENV["SLACK_TOKEN"]}" unless is_ci
end

desc "Tag repository"
lane :tag do |lane|
if !lane[:version]
  raise "No version specified!".red
end
add_git_tag(tag: "#{lane[:version]}")
push_git_tags(force: true)
end

desc "Generate documetation set"
lane :doc do
  sh("cd ../ && bash Scripts/build_docs_set.sh")
end

desc "Test targets"
lane :test do
  ["iOS", "macOS"].each do |platform|
    scan(
      scheme: "MyKit-#{platform}",
      xcargs: "CODE_SIGN_IDENTITY='' CODE_SIGNING_REQUIRED='NO'",
      output_directory: "./.fastlane/test_output",
      custom_report_file_name: "report_#{platform}.html",
      output_types: "html",
      clean: true
    )
  end
end

error do |lane, exception|
  slack(message: exception.message, success: false) unless is_ci
end
