fastlane_version "1.104.0"

before_all do
  is_ci ? nil : ENV["SLACK_URL"] = "https://hooks.slack.com/services/#{ENV["SLACK_TOKEN"]}"
end

desc "Tag repository"
lane :tag do |lane|
if !lane[:version]
  raise "No version specified!".red
end
add_git_tag(tag: "#{lane[:version]}")
push_git_tags(force: true)
end

desc "Generate documetation set"
lane :doc do
  sh("cd ../ && bash Scripts/build_docs_set.sh")
end

desc "Test targets"
lane :test do
  scan(
    scheme: "MyKit-iOS",
    output_directory: "./.fastlane/test_output",
    custom_report_file_name: "report_ios",
    clean: true
  )
  scan(
    scheme: "MyKit-macOS",
    output_directory: "./.fastlane/test_output",
    custom_report_file_name: "report_macos",
    clean: true
  )
end

error do |lane, exception|
  slack(message: exception.message, success: false)
end
